Faq
hack-rpi/HackRPI-Website-2024 pull request #19
Opened 2024-02-27 23:29 UTC by Jordan231111

# Enter Title of Your Pull Request Here
Faq page created
## Please briefly describe the changes made in your pull request below
Implementation of the FAQ page

## If your changes made visual updates to the website, please add screenshot(s) below
NOTE THE IMAGE IS ZOOMED OUT
![image](https://github.com/hack-rpi/HackRPI-Website-2024/assets/79342877/a1f0fb07-a652-43ef-9c0c-de9253dfaa28)

2024-02-29 00:30 UTC, CooperW824 requested changes
This is a great start! Thank you so much Jordan! I suggested some changes for the FAQs to improve code quality and the design. This is a great start!

2024-02-29 00:30 UTC, CooperW824 commented on pages/daisyUI.tsx
Remove this file, we don't want junk files in the repo

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
Lets make this a component instead of a page, we are going to put FAQs on the home page so they are easily accessible.

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
> +			"November 4th-5th 2024, is the date for our 11th annual HackRPI. Arrival and check-in will take place from 10-11am with the opening ceremony beginning at 11am. The event will end at 4pm on Sunday,
Lets update this to have the new date for this year, November 9th and 10th 2024.

2024-02-29 00:30 UTC, CooperW824 commented on pages/index.tsx
> +
Lets remove this comment, its not necessary and doesn't add anything to the code

2024-02-29 00:30 UTC, CooperW824 commented on tsconfig.json
lets revert this change, we shouldn't be using .jsx anywhere in the codebase

2024-02-29 00:30 UTC, CooperW824 commented on pages/.codiumai.toml
delete this file, we don't use automated tests yet and we should avoid junk files

2024-02-29 00:30 UTC, CooperW824 commented on package.json
> +		"react-bootstrap": "^2.10.0",
We don't use bootstrap anywhere in the project, we should remove this dependency

2024-02-29 00:30 UTC, CooperW824 commented on components/nav-bar/nav-bar.tsx
> +		{ href: "/faq", children: "FAQ" },
We aren't going to have an FAQ page like we did last year, so lets remove this link

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
It looks like the top border and bottom border are thinner than the middle borders, can you fix that too?
![image](https://github.com/hack-rpi/HackRPI-Website-2024/assets/77216025/6b4b7a79-2902-4fe0-900a-a052a879263c)

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
> +			<div className="w-full md:w-3/4 lg:w-3/4 mx-auto">
I know I said 3/4 width but it looks too wide, lets do 1/2 width, and lets keep it at 1/2 width for all screen sizes (i.e. lets remove the media queries)

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
> +						<div className="collapse-title font-medium text-4xl text-hackrpi-primary-blue">{faq.title}</div>
This title text is a bit too big, lets make this like text-2xl

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
> +					Feel free to contact us with any other questions at{" "}
lets make this text a bit bigger, maybe text-2xl, and make the padding a bit smaller like pt-10

2024-02-29 00:30 UTC, CooperW824 commented on pages/faq.tsx
> +				<h1 className="font-mokoto font-normal text-white text-left text-3xl text-shadow-md pb-10">FAQs</h1>
Lets reduce this padding to maybe pb-4 and make the text bigger so that its more clear this is our FAQs section.

2024-03-01 20:11 UTC, Jordan231111 commented on tsconfig.json
can you explain a bit more, how would i fix it do i change that jsx to tsx?

	"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "pages/daisyUI.jsx"],

2024-03-01 20:46 UTC, Jordan231111 commented
I have fixed all the issues, except not too sure about the jsx

2024-03-01 21:19 UTC, CooperW824 commented on tsconfig.json
You can just  change the line so that it says:
`"include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"]`
Instead, so that we remove the .jsx file from the tsconfig.

2024-03-01 21:26 UTC, CooperW824 approved these changes
LGTM

2024-03-01 21:26 UTC, merged

2024-03-01 21:26 UTC, CooperW824 commented
Merged! Fantastic Job Jordan!