About Us Component
hack-rpi/HackRPI-Website-2024 pull request #29
Opened 2024-03-12 20:41 UTC by sdhoat

About Us Component

Section to be added on the home page, which is a description of the event.

2024-03-15 20:41 UTC, CooperW824 requested changes
This is a really great start! Try to make the changes listed, if you have any questions, let me know or feel free to shoot me a message.

2024-03-15 20:41 UTC, CooperW824 commented on pages/about-us.tsx
> +      <h1 className="text-white text-5xl mb-4 font-hveltica">About Us</h1>
"font-hveltica" should be "font-sans" to use the Helvetica font.
Lets also add "font-bold" to make this a bit more important.

2024-03-15 20:41 UTC, CooperW824 commented on package.json
> +		"bootstrap": "^5.3.2",
remove this dependency, we don't use bootstrap on the project and so it shouldn't be in the package.json

2024-03-15 20:41 UTC, CooperW824 commented on package.json
> +		"react-bootstrap": "^2.10.0",
remove this dependency too, we don't use bootstrap on the project and so it shouldn't be in the package.json

2024-03-15 20:41 UTC, CooperW824 commented on package-lock.json
this file shouldn't change after you remove the bootstrap dependencies and run `npm i`

2024-03-15 20:41 UTC, CooperW824 commented on pages/about-us.tsx
> +              <img src={calendarImage.src} alt="Calendar" className="mr-2" />
You should use [Next's Image Component](https://nextjs.org/docs/pages/api-reference/components/image), it provides image optimization like compression, lazy loading etc...

2024-03-15 20:41 UTC, CooperW824 commented on pages/about-us.tsx
> +              <img src={locationImage.src} alt="Location" className="mr-2" />
You should use [Next's Image Component](https://nextjs.org/docs/pages/api-reference/components/image), it provides image optimization like compression, lazy loading etc...

2024-03-15 20:41 UTC, CooperW824 commented on pages/about-us.tsx
move this file into the components directory so that it reads `components/about-us.tsx`

2024-03-15 20:41 UTC, CooperW824 commented on pages/about-us.tsx
> +              <img src={locationImage.src} alt="Location" className="mr-2" />
Can you fix this issue when the screen width gets to be smaller? 
![image](https://github.com/hack-rpi/HackRPI-Website-2024/assets/77216025/e6892323-2e14-447a-b4e0-d89d0c44c970)

2024-03-15 20:41 UTC, CooperW824 commented on pages/index.tsx
Try to run `git pull origin main` and merge in all the changes from the main branch, then add your component.

2024-03-19 21:05 UTC, CooperW824 requested changes

2024-03-19 21:05 UTC, CooperW824 commented on components/link.tsx
lets delete this file as its outdated

2024-03-19 21:05 UTC, CooperW824 commented on pages/about-us.tsx
> +						Come join us this November 9-10, 2024 to hack, learn, and meet other people! We are a motivated team of RPI
Instead of using `<br/>` tags, make these into different `<p>` elements and space them using some amount of margin.

2024-03-19 21:05 UTC, CooperW824 commented on pages/about-us.tsx
> +						<br />
same thing as above, remove the `<br>` tag and make this into multiple paragraphs.

2024-03-19 21:05 UTC, CooperW824 commented on pages/about-us.tsx
> +	};
this is not needed, lets remove this unused code.

2024-03-19 21:05 UTC, CooperW824 commented on pages/about-us.tsx
> +import React, { useState } from "react";
you don't need useState for this component

2024-03-26 22:27 UTC, sdhoat commented
I have added to and fixed all the comments.

2024-04-02 20:26 UTC, sdhoat commented
I have resolved all errors and NextJS workflow runs.

2024-04-22 02:00 UTC, CooperW824 requested changes

2024-04-22 02:00 UTC, CooperW824 commented on components/about-us.tsx
> +						<p style={paragraphStyle}>
I would use tailwind for this instead, if you want to repeat styles without repeating the same string over and over again, you can make the tailwind styles a constant variable and then use that as the class name.

2024-05-03 01:34 UTC, merged