Sponsor us page implemented
hack-rpi/HackRPI-Website-2024 pull request #36
Opened 2024-03-26 21:27 UTC by Jordan231111

Sponsor Us Page Complete
**Important** PLEASE RUN the following command to make sure updates are in sync
npm i

## Please briefly describe the changes made in your pull request below
- Added a new page called sponsor-us-page.tsx that will be used for Sponsors to be informed on how they can sponsor our hackathon. 
- Updated important libraries and packages.

## If your changes made visual updates to the website, please add screenshot(s) below
![opera_Jas5nKO56E](https://github.com/hack-rpi/HackRPI-Website-2024/assets/79342877/6388ae93-57c1-47c0-a9bc-301b2c88f1f0)

2024-04-04 21:57 UTC, CooperW824 requested changes
This is a great start, marketing recently came back with the planned design for this year, do you think you could make it look like the figma design? https://www.figma.com/file/qrB2VTaRf47vtW6oTNUYos/Mockup?type=design&node-id=197%3A308&mode=design&t=SVnOqfXNQ2Co2Rjz-1

This is a really good start, and seems like this should be a pretty minor adjustment.

2024-04-04 21:57 UTC, CooperW824 commented on pages/sponsor-us-page.tsx
> +						className="w-full h-[60vh] lg:h-[60vh]" // Adjusted height
This comment is a bit redundant, also its redundant to have a media query that scales to the same size as its orignal sizes. Lets also use css aspect ratio to set the height so that the height scales with the width.
```suggestion
						className="w-full aspect-[8.5/11]"
```

2024-04-04 21:57 UTC, CooperW824 commented on pages/sponsor-us-page.tsx
> +					<h1 className="text-2xl font-bold mb-4">Want to support?</h1>
add `mr-5` to the class name to do this instead and maybe we set a defined width of 350px 
```suggestion
				<div className="flex flex-col items-center w-[350px] p-2 mr-5">
```

2024-04-04 21:57 UTC, CooperW824 commented on pages/sponsor-us-page.tsx
> +			<div className="flex justify-center w-full">
As this is right now, the embeds are positioned horizontally, this doesn't work well on mobile. You can add a css media query that positions them vertically on small devices like so: `flex-row sm:flex-col`

2024-04-04 21:57 UTC, CooperW824 commented on pages/sponsor-us-page.tsx
> +				<div className="flex flex-col items-center w-full lg:w-1/2 p-2" style={{ marginLeft: "20px" }}>
Lets also adjust the width and the aspect ratio for this element like the element above.

2024-04-04 21:57 UTC, CooperW824 commented on pages/sponsor-us-page.tsx
> +					></iframe>
for both of these iframes, we should probably just bundle the pdfs with the site, and embed them using html `<embed>` tags.

2024-04-04 21:57 UTC, CooperW824 commented on pages/sponsor-us-page.tsx
> +					></iframe>
I can show you how to do that in RCOS.

2024-04-05 00:57 UTC, Jordan231111 commented on package.json
I think it is very redundant for another PR and I took rcos last semester and was told that minor updates with packages should be merged along with commits.

2024-04-05 20:33 UTC, Jordan231111 commented on pages/sponsor-us-page.tsx
> +					<h1 className="text-2xl font-bold mb-4">Want to support?</h1>
Unsure how to apply this as it completly broke the sizing

2024-04-05 20:38 UTC, Jordan231111 commented on pages/sponsor-us-page.tsx
> +						className="w-full h-[60vh] lg:h-[60vh]" // Adjusted height
Unsure if that code broke the height or its because of invalid URL.

2024-04-05 20:49 UTC, CooperW824 commented on package.json
See, the comment I made on the issue about this, but the TLDR of it is that, doing separate PRs for dependency bumps and for features does 3 things: 
1. Reduces bugs.
2. Improves Compatibility
3. Improves Security

2024-04-09 20:55 UTC, CooperW824 approved these changes
Great Job! Thanks for doing this! It looks great!

2024-04-09 20:55 UTC, merged