Feature/previous projects
hack-rpi/HackRPI-Website-2024 pull request #71
Opened 2024-06-06 01:52 UTC by Jordan231111

## Please briefly describe the changes made in your pull request below
Implemented the entire previous projects from 2023 page

### Known Issues
- Mobile scaling
- next js routing

## If your changes made visual updates to the website, please add screenshot(s) below
![image](https://github.com/hack-rpi/HackRPI-Website-2024/assets/79342877/8df3c4ee-4abb-4042-9736-2f9a81afab82)

2024-06-09 00:57 UTC, CooperW824 requested changes
So this looks pretty good so far. Thank you! For components like the carousel I usually prefer to find a library that does it for me so that I don't have to worry about all the complicated logic of the component and making sure it sizes dynamically. Also do you think you could add the prize categories to the site? So that visitors see which projects won what.

You might want to check out this cool component I found on NPM: https://www.npmjs.com/package/react-multi-carousel

2024-06-09 00:57 UTC, CooperW824 commented on app/last-year/page.tsx
> +						<img
I would replace this with Next's Image component, just for consistency and image optimization.

2024-06-09 00:57 UTC, CooperW824 commented on components/prev-projects/Arrow.tsx
You could remove this file if you switch to pre-built component

2024-06-18 23:34 UTC, Jordan231111 commented
> So this looks pretty good so far. Thank you! For components like the carousel I usually prefer to find a library that does it for me so that I don't have to worry about all the complicated logic of the component and making sure it sizes dynamically. Also do you think you could add the prize categories to the site? So that visitors see which projects won what.
> 
> You might want to check out this cool component I found on NPM: https://www.npmjs.com/package/react-multi-carousel

Is there a way to do it without the library that seems more complicated and also not sure how I would use that and still match the figma design.
I am also confused how I would add prize categories where would it go?

2024-06-19 00:00 UTC, CooperW824 commented
The way that image carousels like this one are implemented are usually done by having a parent div with a fixed width and the css property `overflow-x: hidden`. Inside that div you have a list of all the carousel elements, each element has the same width as the parent div. Then when the user clicks a button, you just set the translation (x-movement) of all the carousel items to be offset left or right by the width * visible_index (i.e. which item is visible). Your approach also works well, if you wanted to get fancy without changing too much of the logic, you could do a fade-out, fade-in type of thing without adding too much logic using `requestAnimationFrame()`. 

Another thing that is important the Figma designs are not the end all be all, they are a suggestion for the layout, but ultimately the developer has the final say on the layout and design. If you want you could move the buttons, change their sizes, change colors, etc. I strongly encourage you to change the designs as the design for the buttons on Figma was not supposed to be like that on the site.

Lastly, about the prize categories, I would recommend placing them under the project title in maybe smaller font? Ultimately its up to you as the dev.

2024-08-05 01:33 UTC, merged